### ISSUE TITLE
Keine installation möglich

### ISSUE THREAD

**Issue by sash85** [shopwareLabs/SwagGoogle#1]
Hallo,

ich habe versucht das Plugin über den Pluginmanager zu installieren. Da dies nicht funktionierte habe ich die Daten via ftp hochgeladen (…plugins/Community/Core/SwagGoogle), was ebenfalls nicht funktioniert.

Beim starten des Pluginmanagers erhalte ich folgenden Fehler:
    Fatal error: Class 'Shopware_Plugins_Core_SwagGoogle_Bootstrap' not found in …/engine/Shopware/Components/Plugin/Namespace.php on line 256 503 Service Unavailable

Kann mir jemand weiter helfen?

**Comment by bcremer** [comment]
Hi,

das SwagGoogle Plugin muss innerhalb des `Frontend` Ordners installiert werden, nicht in `Core`.
Dann sollte die Installation Problemlos durchlaufen.

**Comment by sash85** [comment]
Vielen Dank!
