### ISSUE TITLE
.githooks accessible after plugin deployment

### ISSUE THREAD

**Issue by robert-scheck** [shopwareLabs/SwagGoogle#11]
Currently, e.g. with release/tag 3.0.2, the `.githooks` directory is part of the release tarball and thus it is also accessible after the deployment of the plugin. This is not directly critical given the `.githooks` directory does not (yet?) contain sensible information but it might make software security scanners yelling and you also never know what happens at forks. Thus my proposal is to add a `.htaccess` file to restrict the access for the `.githooks` directory simply.

**Comment by mitelg** [comment]
hey @robert-scheck 
sorry for the late response. this directory is part of every plugin of us and only installs the githook and executes it. some code style fixing, etc is going on there. so nothing security critical
