### ISSUE TITLE
Invalid/superflous round of ordernumber

### ISSUE THREAD

**Issue by mschop** [shopwareLabs/SwagGoogle#14]
Hi,

the file `ua.tpl` contains a bug in this line:

https://github.com/shopwareLabs/SwagGoogle/blob/master/Resources/views/frontend/swag_google/ua.tpl#L41

the plugin does a superflous and invalid round on the ordernumber of a created order. If the ordernumber is not just a counted number (which is the default in Shopware) but is prefixed or suffixed, the round returns 0 instead of the original ordernumber.

The ordernumber is a string and not a number. Because of this, the round is superflous and incorrect.

Best Regards
mschop

**Comment by mitelg** [comment]
hey @mschop 
thanks for the issue :+1: I made a quick commit to fix it
