### ISSUE TITLE
Switch für header / footer include

### ISSUE THREAD

**Issue by tim-bec** [shopwareLabs/SwagGoogle#2]
Google empfiehlt den analytics-Code vor dem schließenden /head einzufügen. ( https://developers.google.com/analytics/devguides/collection/analyticsjs/ )
Ich verstehe warum das Javascript standardmäßig im Footer platziert wird. Jedoch macht das einbinden des GA Codes im Footer oft beim exakten Tracking Probleme.

Vielleicht wäre ein guter Kompromiss ein switch der Wahlweise in `frontend_index_header` oder wie bisher `frontend_index_header_javascript` extended.

Einen Pull-Request kann ich ggf. beisteuern.

**Comment by klarstil** [comment]
@tim-bec Ich sehe aktuell leider nicht das Problem. Einen Block einzubauen, worin der Code dann eingebaut werden kann ist natürlich kein Problem.

Das Skript macht ja nichts als ein anderes Skript nachzuladen und einen Request an Google zu senden. Dieser Prozess läuft bereits asynchron ab, weshalb ich kein Problem sehe warum das Tracking nicht richtig funktionieren sollte.

**Comment by tim-bec** [comment]
@klarstil - Danke für eure schnelle Antwort. Mit der Einbindung im Footer gibt es ( vor allem in Kombination mit Adwords) immer mal Abweichungen in den Daten zwischen 5-15%. Mit einer Einbindung in den header erreichen wir hingegen fast 100%

**Comment by klarstil** [comment]
@tim-bec Danke für die Antwort. Ich habe das Problem intern abgesprochen. Wir werden es so machen, dass wir einen neuen Block mit Shopware 5.1 in den Core einbauen und einen Switch wie vorgeschlagen im Plugin zur Verfügung stellen, damit die Position der Einbindung festgelegt werden kann.

**Comment by klarstil** [comment]
Ich lasse die Issue so lange auf bis wir den Block eingebaut haben.

**Comment by tim-bec** [comment]
@klarstil sauber. Besten Dank!

**Comment by klarstil** [comment]
Hier schon mal der Block: https://github.com/shopware/shopware/commit/f325b3b2c056875f4be7d5288d7d435b09f0e9df

**Comment by klarstil** [comment]
@tim-bec Der Switch ist jetzt drin :) Daher mache ich das Ticket zu
