### ISSUE TITLE
SmartyException during Ajax Call

### ISSUE THREAD

**Issue by bucsithte** [shopwareLabs/SwagGoogle#8]
Hello,

in one of our customer shops we encountered the following exception on an article detail page when using the SwagGoogle Plugin:
`SmartyException: directory /custom/plugins/SwagGoogle/Views/frontend/index/index.tpl' not allowed by security setting in /engine/Library/Smarty/sysplugins/smarty_security.php:38`

The security issue seems to be forced due to the current order of the ajax request check and the template registration in the **onPostDispatch** method:

We could fix this issue by changing the order of the ajax request check and the template registration:

```php
$view->addTemplateDir($this->getPath() . '/Resources/views');

if ($request->isXmlHttpRequest()) {
    return;
}
```

**instead of**:

```php
if ($request->isXmlHttpRequest()) {
    return;
}

$view->addTemplateDir($this->getPath() . '/Resources/views');
```

Could you please verify this patch solution?

**Comment by mitelg** [comment]
hey @bucsithte 
you are right, the `addTemplateDir` should come first. Would you like to create a PR for that?

**Comment by bucsithte** [comment]
hey @mitelg 

yes, done: #9

**Comment by mitelg** [comment]
closing, as the PR is already merged
